"""
Find anomalous elliptic curves (trace of Frobenius = 1).

An elliptic curve E/GF(p) is anomalous when #E(GF(p)) = p.
This script provides two methods:

1. Brute-force search over small primes: try all (a, b) pairs
   until #E = p.
2. CM construction for large primes: use the theory of complex
   multiplication to construct anomalous curves directly.
   For j=0 (discriminant D=-3), an anomalous curve exists when
   4p = 1 + 3*s^2 for odd s, giving y^2 = x^3 + b.

Usage:
  sage find_anomalous_curves.sage
"""


# This file was *autogenerated* from the file scripts/find_anomalous_curves.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_27 = Integer(27); _sage_const_2 = Integer(2); _sage_const_50000 = Integer(50000); _sage_const_30 = Integer(30); _sage_const_31 = Integer(31); _sage_const_43 = Integer(43); _sage_const_53 = Integer(53); _sage_const_97 = Integer(97); _sage_const_157 = Integer(157); _sage_const_181 = Integer(181); _sage_const_128 = Integer(128); _sage_const_192 = Integer(192); _sage_const_256 = Integer(256); _sage_const_381 = Integer(381)

def find_small(p, require_a_nonzero=False):
    """
    Find an anomalous curve over GF(p) by brute-force search.
    Practical for primes up to a few hundred.

    INPUT:
    - p: a prime number
    - require_a_nonzero: if True, skip curves with a=0

    OUTPUT:
    - (a, b) such that #E(GF(p)) = p for y^2 = x^3 + ax + b,
      or None if not found
    """
    F = GF(p)
    start_a = _sage_const_1  if require_a_nonzero else _sage_const_0 
    for a in range(start_a, p):
        for b in range(p):
            if (_sage_const_4  * a**_sage_const_3  + _sage_const_27  * b**_sage_const_2 ) % p == _sage_const_0 :
                continue
            E = EllipticCurve(F, [a, b])
            if E.order() == p:
                return (a, b)
    return None


def find_large_cm(target_bits, max_attempts=_sage_const_50000 ):
    """
    Construct an anomalous curve over a prime of approximately
    target_bits bits using CM with j=0 (discriminant D=-3).

    For trace t=1: 4p = t^2 + 3*s^2 = 1 + 3*s^2.
    We need s odd for p = (1 + 3*s^2)/4 to be an integer.
    The resulting curve is y^2 = x^3 + b for some small b.

    INPUT:
    - target_bits: desired bit-length of the prime
    - max_attempts: number of values of s to try

    OUTPUT:
    - (p, a, b) where a=0 and #E(GF(p)) = p, or None
    """
    # Start s near 2^(target_bits/2) so that p ~ 2^target_bits
    s_start = ZZ(_sage_const_2 )**(target_bits // _sage_const_2 )
    if s_start % _sage_const_2  == _sage_const_0 :
        s_start += _sage_const_1 

    for delta in range(_sage_const_0 , max_attempts, _sage_const_2 ):
        s = s_start + delta
        p_candidate = (_sage_const_1  + _sage_const_3  * s**_sage_const_2 ) // _sage_const_4 
        if not p_candidate.is_prime():
            continue
        if p_candidate.nbits() < target_bits - _sage_const_1 :
            continue
        F = GF(p_candidate)
        # Try small values of b for y^2 = x^3 + b
        for b_val in range(_sage_const_1 , _sage_const_30 ):
            try:
                E = EllipticCurve(F, [_sage_const_0 , b_val])
                if E.order() == p_candidate:
                    return (p_candidate, _sage_const_0 , b_val)
            except ArithmeticError:
                continue
    return None


if __name__ == "__main__":
    print("=== Small primes (brute-force) ===")
    print()
    for p in [_sage_const_31 , _sage_const_43 , _sage_const_53 , _sage_const_97 , _sage_const_157 , _sage_const_181 ]:
        result = find_small(p)
        if result:
            a, b = result
            print(
                "p=%d: y^2 = x^3 + %d*x + %d" % (p, a, b)
            )
        # Also find one with a != 0 if the first had a=0
        result_nz = find_small(p, require_a_nonzero=True)
        if result_nz and result_nz != result:
            a, b = result_nz
            print(
                "p=%d: y^2 = x^3 + %d*x + %d (a != 0)"
                % (p, a, b)
            )

    print()
    print("=== Large primes (CM construction, j=0) ===")
    print()
    for bits in [_sage_const_128 , _sage_const_192 , _sage_const_256 , _sage_const_381 ]:
        result = find_large_cm(bits)
        if result:
            p, a, b = result
            print(
                "%d-bit: y^2 = x^3 + %d*x + %d"
                % (p.nbits(), a, b)
            )
            print("  p = %d" % p)
        else:
            print(
                "%d-bit: no curve found" % bits
            )

