"""
Smart's attack on anomalous elliptic curves.

Solves the ECDLP in linear time when #E(F_p) = p, using the
p-adic formal group logarithm.

Reference:
  Nigel Smart, "The Discrete Logarithm Problem on Elliptic
  Curves of Trace One", Journal of Cryptology, 1999.
"""


# This file was *autogenerated* from the file scripts/smart_attack.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_43 = Integer(43); _sage_const_97 = Integer(97); _sage_const_157 = Integer(157); _sage_const_14 = Integer(14); _sage_const_57 = Integer(57); _sage_const_2 = Integer(2); _sage_const_13 = Integer(13); _sage_const_5 = Integer(5)

def smart_attack(P, Q, p):
    """
    Solve Q = n*P on an anomalous curve E/GF(p)
    using the p-adic formal group logarithm.

    INPUT:
    - P: a point on E(GF(p)), the generator
    - Q: a point on E(GF(p)), the target
    - p: the prime defining the base field

    OUTPUT:
    - n such that Q = n * P
    """
    E = P.curve()

    # Lift the curve to Q_p. We perturb the a-invariants by
    # random multiples of p so the lifted curve is not the
    # canonical lift. On the canonical lift, p * P_lift is the
    # identity (because E is anomalous), which makes the
    # logarithm trivially zero. Perturbing gives a different
    # lift where p * P_lift lands in the formal group kernel
    # but is nonzero, allowing us to read off the logarithm.
    ainvs = E.a_invariants()
    lifted = [
        ZZ(t) + ZZ.random_element(_sage_const_0 , p) * p for t in ainvs
    ]
    Ep = EllipticCurve(Qp(p, _sage_const_8 ), lifted)

    # Lift points: find the root of lift_x whose y-coordinate
    # reduces to the correct value mod p.
    def lift_point(R):
        x, y = R.xy()
        candidates = Ep.lift_x(ZZ(x), all=True)
        for pt in candidates:
            if GF(p)(pt.xy()[_sage_const_1 ]) == y:
                return pt
        raise ValueError("Could not lift point %s" % R)

    P_lift = lift_point(P)
    Q_lift = lift_point(Q)

    # Map into the formal group via p-multiplication.
    # For a non-canonical lift, p * P_lift reduces to the
    # identity mod p (since P has order p in E(F_p)), so it
    # lies in the kernel of reduction, i.e. the formal group.
    pP = p * P_lift
    pQ = p * Q_lift

    # Extract the formal group logarithm.
    # For a point (x, y) in the formal group with v(x) < 0,
    # the local parameter is t = -x/y, and log(t) = t + ...
    # To first order, the logarithm is just t itself.
    log_P = -(pP.xy()[_sage_const_0 ] / pP.xy()[_sage_const_1 ])
    log_Q = -(pQ.xy()[_sage_const_0 ] / pQ.xy()[_sage_const_1 ])

    # Discrete log is now division in Q_p, reduced mod p.
    return ZZ(log_Q / log_P) % p


def test_smart_attack():
    """
    Test Smart's attack on known anomalous curves.

    We verify the attack across several primes and secrets.
    A curve y^2 = x^3 + a*x + b over GF(p) is anomalous
    when #E(GF(p)) = p.
    """
    # (p, a, b) triples for anomalous curves
    # Small primes for fast sanity checks
    p_43 = _sage_const_43 
    p_97 = _sage_const_97 
    p_157 = _sage_const_157 
    # 256-bit prime (constructed via CM with j=0, trace=1)
    p_256 = Integer(
        "868440669279871465676782387565159309016"
        "92230158002800019079611962330850525581"
    )
    # 380-bit prime (constructed via CM with j=0, trace=1)
    p_380 = Integer(
        "184696904045599121307558000469423189711"
        "311277830306781316503193307190956665360"
        "5953071682581549594926623032013275521"
    )

    test_curves = [
        (p_43, _sage_const_1 , _sage_const_14 ),
        (p_97, _sage_const_1 , _sage_const_1 ),
        (p_157, _sage_const_1 , _sage_const_57 ),
        (p_256, _sage_const_0 , _sage_const_2 ),
        (p_380, _sage_const_0 , _sage_const_13 ),
    ]

    for p, a, b in test_curves:
        F = GF(p)
        E = EllipticCurve(F, [a, b])

        order = E.order()
        assert order == p, (
            "Curve is not anomalous: "
            "#E(F_%d) = %d != %d" % (p, order, p)
        )

        P = E.gens()[_sage_const_0 ]

        for _ in range(_sage_const_5 ):
            secret = ZZ.random_element(_sage_const_1 , p)
            Q = secret * P
            recovered = smart_attack(P, Q, p)
            assert recovered == secret, (
                "Attack failed on p=%d: "
                "recovered %d, expected %d"
                % (p, recovered, secret)
            )

        print(
            "PASS: y^2 = x^3 + %d*x + %d over GF(%d-bit)"
            % (a, b, p.nbits())
        )

    print("All Smart's attack tests passed.")


if __name__ == "__main__":
    test_smart_attack()

